#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo
echo 'Running Commit-Message GitHook...'
echo

dotnet husky run --name "commit-message-linter" --args "$1"
echo
echo 'Message Accepted. Committing changes...'
echo
