#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo
echo 'Runnig Pre-Commit GitHook...'

echo
echo 'Formatting...'

dotnet husky run --name dotnet-format-staged-files

echo
echo 'Building...'

dotnet build

echo
echo 'Testing...'

dotnet test

echo
