#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo
echo 'Runnig Pre-Commit GitHook...'

echo
echo 'Formatting...'

dotnet husky run --name dotnet-format-staged-files

echo
echo 'Building...'

dotnet husky run --name build-solution

echo
echo 'Testing...'

dotnet husky run --name run-tests

echo
